apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward
spec:
  template:
    spec:
      containers:
      - name: steward
        image: ghcr.io/profianinc/steward@sha256:f60eeb8a33dda5c6a48c69cc52868f7473bf306940848b01885dd2c0f37371a3
        imagePullPolicy: IfNotPresent
