apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- ../../base/drawbridge
namespace: drawbridge-staging
patches:
- patch-certificate.yaml
- patch-deployment.yaml
- patch-ingress.yaml
